### ISSUE TITLE
bug: applyer do not consume

### ISSUE THREAD

**Issue by zeusYi** [tom--bo/mysql-query-replayer#1]
1、start observer 
./observer -rh 192.168.184.32 -rP 6379 -mP 3306 -d any -name capture &

2、
The source IP of the source database program is :
192.168.184.33 
192.168.184.32

3、So I create two applyer to consume two  mq redis key (capture:192.168.184.33:59222, capture:192.168.184.32:59646)
 ./applyer -A -mh 192.168.184.31 -mP 3306 -mu root -md sbtest -rh 192.168.184.32  -mp Root@123  -name capture:192.168.184.33 -p 6061 
 ./applyer -A -mh 192.168.184.31 -mP 3306 -mu root -md sbtest -rh 192.168.184.32  -mp Root@123  -name capture:192.168.184.32 -p 6062 

./applyer -M -agents 192.168.184.31:6061,192.168.184.31:6062 -rh 192.168.184.32 -name capture 

4、target db is : 192.168.184.31

problem:
After a while, I found that the list llen of one of the redis keys only increased and did not decrease. I logged into the target db and showed the processlist. I found that only one thread was executing the QUERY, and only the invisible redis key was added. Already.

**Comment by zeusYi** [comment]
d

**Comment by tom--bo** [comment]
Sorry, I noticed just now. I'll check it.
